### ISSUE TITLE
Not really an issue 

### ISSUE THREAD

**Issue by tomredhot** [addyire/ha-menu#1]
Hi,
First of all: Thanks! This is amazing & work like a charm. I'm on mac with M1 chipset, but this run perfectly. 
2 littles things yet :
- why "sepErator" & not "sepArator" ? 
- I don't find in documentation where configure the label in the mac os menu bar. In this printscreen, we can see temperature beside HA icon but no mention on documentation. 
![image](https://user-images.githubusercontent.com/5106847/141473178-17705485-0c23-44b4-bacd-ec3e22d29485.png)

Thanks again!
Tom

**Comment by addyire** [comment]
will fix the spelling in a later release. the title can be configured by adding "title" to the json. if you search on the readme for title you should find it. i will make this more clear in the readme.
