### ISSUE TITLE
Auto reconnect functionality

### ISSUE THREAD

**Issue by lkucytowski** [addyire/ha-menu#3]
Firstly, Thank You for the ha-menu, amazing project! I was wondering if it would be possible to implement some kind of auto reconnect functionality where the software tries to reconnect for x amount of time after losing connection to the HA? I hit the following scenario where it would be very useful to have it;
I set ha-menu to start with MacOS and it starts just fine, however, next in the queue is AdGuard which is taking a significant time to load. Due to the specifics of this software, it's causing the network connection to reset and in the result of that ha-menu gets disconnected and I have to reconnect it manually.

**Comment by addyire** [comment]
The app will retry on the next refresh interval which can be changed in the settings. I could make the app retry more frequently if it fails to connect, if you would be interested in that.
