### ISSUE TITLE
Failure to connect to HA despite Validate Connection

### ISSUE THREAD

**Issue by AndyBerman** [addyire/ha-menu#4]
I just installed HA version 2.1.0 on my Windows 10 PC.   The validate Connection button works, but then it immediately says it failed to connect to HA.  The icon in the Taskbar is Red. 

See screenshot below:

<img width="421" alt="github1" src="https://user-images.githubusercontent.com/6676165/144712552-d6b08ed8-b71c-42c8-b0bc-3bcc228b00fc.png">

Is there a Log file I can look at?  Thanks

**Comment by addyire** [comment]
try adding `http://` infont of the server url

**Comment by AndyBerman** [comment]
Ah, that was it.  Thanks for the quick response!  It looks great.
