### ISSUE TITLE
Ability to hide home assistant icon

### ISSUE THREAD

**Issue by kacper-serewis** [addyire/ha-menu#5]
I'm using title templating and would love to hide (unneeded for me) home assistant icon before the template.
![How it looks now](https://user-images.githubusercontent.com/16763276/146905343-05cb3bb2-71c9-44d3-8349-afc5a41a8298.png)

**Comment by addyire** [comment]
I will look into adding a feature to hide the icon, though it may not be possible because of Electrons limitations.

**Comment by addyire** [comment]
Not possible with electron.
