### ISSUE TITLE
405: Method not allowed error

### ISSUE THREAD

**Issue by franzuu** [addyire/ha-menu#6]
Hi!
First of all thank you for this cool app!
I tried the included example, but getting this error: 405: Method not allowed
![Screen Shot 2022-02-08 at 23 57 08](https://user-images.githubusercontent.com/18600583/153082638-efc86085-7b7f-47d1-9c1f-be54348cfbb9.png)

Connection to HA seems to work only with Nabu Casa connection (https). I couldn't get it to connect with local network (tried adding http:// in front of the ip, but didn't work).
System:
macos: 10.13.6,
app version: v2.1.0

Hope it is easy fix

**Comment by addyire** [comment]
Verify that you have the correct IP and port. If that does not fix the problem try cloning the repo and running it from the source code and look for any errors.
