### ISSUE TITLE
"HA Menu.app is damaged and can’t be opened" error on macOS 12.6

### ISSUE THREAD

**Issue by gquach** [addyire/ha-menu#7]
Is anybody else getting this error when trying to run HA Menu.app from the latest v2.1.0 release?
https://github.com/addyire/ha-menu/releases/tag/v2.1.0
<img width="372" alt="Screen Shot 2022-10-13 at 22 15 44" src="https://user-images.githubusercontent.com/9689284/195582704-c62ca578-1217-487d-b74f-583f40749c8d.png">

I've tried all the .zip files and .dmg files and they all give me this error, strange.

Have tried downloading these files in Safari, Chrome and Firefox, and still get the same error when trying to run the app.

(This is on an M1 Max MacBook Pro, running macOS 12.6)

**Comment by dominickolbe** [comment]
Prob to late but maybe helpful for others:
`sudo xattr -cr /Applications/HA\ Menu.app`

**Comment by gquach** [comment]
@dominickolbe you're awesome, thank you! That has resolved my issue.
