### ISSUE TITLE
Icon Changes based on state

### ISSUE THREAD

**Issue by trackermb** [addyire/ha-menu#9]
Hi was wondering is there anyway to change the icon based on the state of an entity.

eg  when state on "icon": "office-on.png" and when state is off office-off.png.

Have tried a couple of way but can seem to get any to work. 

Here's and example of one that i tried but didn't work 

```
    {
      "type": "label",
      "labelTemplate": "{% if is_state('light.office', 'on') %}Office light is on{% else %}Office light is off{% endif %}",
      "icon": "{% if is_state('light.office', 'on') %}toggle-on.png{% else %}toggle-off.png{% endif %}"
    },
```
Thanks in advance

**Comment by addyire** [comment]
Change `"icon"` to `"iconTemplate"`

**Comment by trackermb** [comment]
Hi thanks for your fast response.  That worked a treat.  Just wondering do you have any plans to edit the refresh down as low as 1 second as when using icons to identify if something is on a minute delay on refresh is a bit long.

Thanks again

**Comment by addyire** [comment]
The icons should refresh when the entire menu bar refreshes. The refresh rate you enter in the preferences is in minutes so just put in `.01666` to refresh every second. Keep in mind this will consume much more power.

**Comment by trackermb** [comment]
Hi thanks for this info but where can i add the refresh number as in preferences I can only see a slider with the lowest being never then 1 minutes, is there a file i can edit?
<img width="761" alt="image" src="https://user-images.githubusercontent.com/7849892/235209760-362589f7-b2e0-4f80-9d95-5c02962c363e.png">
Thanks again

**Comment by trackermb** [comment]
Hi Thanks for that tip but I have changed the to as below in the settings.json but it still is only refreshing every minute.  Seems like it can't accept anything less than 1 mins.  Can you think of a work around as im guessing it would be a lot of work to change mins to seconds

refreshInterval : .01666
